### ISSUE TITLE
<div><table class="column"> vs <table class="column"

### ISSUE THREAD

**Issue by bago** [tutsplus/creating-a-future-proof-responsive-email-without-media-queries#1]
Is there a reason you use a wrapping div for the 2-columns while you direclty put the "content" class in the table for the 3-columns?

Also, you have styles declaring ".column" as display: inline-block but you don't put it back to "display: table" or "display: block" on media query:

I'd expect something like this in the @media query:
```css
	.column {
		display: block !important;
	}
	table.column {
		display: table !important;
	}
```
Otherwise a small content would not push its ".content" to 100%.

Another option would be to use "width" instead of "max-width" in the @media rules, but maybe there is a reason to not use it... any hint?

Thank you for sharing this template!
